CREATE DATABASE BD_MusicSom;

USE BD_MusicSom;

CREATE TABLE TB_RESPONSAVEL
 (
TB_ID_RESPONSAVEL INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_NOME_COMPLETO_RESPONSAVEL VARCHAR(200) NOT NULL,
TB_EMAIL_RESPONSAVEL VARCHAR(50) NOT NULL,
TB_TELEFONE_RESPONSAVEL VARCHAR(20) NOT NULL
);

CREATE TABLE TB_CONTAS_DE_USUARIO 
(
TB_ID_CONTA INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_NOME_CONTA VARCHAR(85) NOT NULL,
TB_SENHA_CONTA VARCHAR(40) NOT NULL,
TB_CARGO_CONTA VARCHAR(60) NOT NULL
);

CREATE TABLE TB_ALUNO 
(
TB_ID_ALUNO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_NOME_ALUNO VARCHAR(85) NOT NULL,
TB_SOBRENOME_ALUNO VARCHAR(85) NOT NULL,
TB_EMAIL_ALUNO VARCHAR(50) NOT NULL,
TB_TELEFONE_ALUNO VARCHAR(20) NOT NULL,
TB_DT_NAS_ALUNO VARCHAR(50) NOT NULL,
TB_CPF_ALUNO VARCHAR(20) NOT NULL,
TB_RG_ALUNO VARCHAR(20) NOT NULL,
TB_CIDADE_ALUNO VARCHAR(50) NOT NULL,
TB_BAIRRO_ALUNO VARCHAR(40) NOT NULL,
TB_CEP_ALUNO VARCHAR(30) NOT NULL,
TB_ENDERECO_ALUNO VARCHAR(64) NOT NULL,
TB_ID_CURSO INTEGER NOT NULL,
TB_STATUS_ALUNO VARCHAR(20) NOT NULL,
TB_DT_MATRICULA_ALUNO VARCHAR(20),
TB_ID_RESPONSAVEL INTEGER,
TB_ID_CONTA INTEGER
);

CREATE TABLE TB_CARGO 
(
TB_ID_CARGO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_NOME_CARGO VARCHAR(120) NOT NULL
);

CREATE TABLE TB_FUNCIONARIO
 (
TB_ID_FUNCIONARIO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_NOME_FUNCIONARIO VARCHAR(85) NOT NULL,
TB_SOBRENOME_FUNCIONARIO VARCHAR(85) NOT NULL,
TB_EMAIL_FUNCIONARIO VARCHAR(50) NOT NULL,
TB_TELEFONE_FUNCIONARIO VARCHAR(20) NOT NULL,
TB_DT_NAS_FUNCIONARIO VARCHAR(20) NOT NULL,
TB_CPF_FUNCIONARIO VARCHAR(20) NOT NULL,
TB_RG_FUNCIONARIO VARCHAR(20) NOT NULL,
TB_CIDADE_FUNCIONARIO VARCHAR(50) NOT NULL,
TB_BAIRRO_FUNCIONARIO VARCHAR(40) NOT NULL,
TB_CEP_FUNCIONARIO VARCHAR(30) NOT NULL,
TB_ENDERECO_FUNCIONARIO VARCHAR(64) NOT NULL,
TB_ESTADO_CIVIL_FUNCIONARIO VARCHAR(20) NOT NULL,
TB_NOME_CURRICULO_FUNCIONARIO VARCHAR(15000),
TB_ARQUIVO_CURRICULO_FUNCIONARIO LONGBLOB,
TB_ID_CARGO INTEGER NOT NULL,
TB_STATUS_FUNCIONARIO VARCHAR(20) NOT NULL,
TB_DT_ADMISSAO_FUNCIONARIO VARCHAR(20),
TB_ID_CURSO INTEGER,
TB_ID_CONTA INTEGER 
);

CREATE TABLE TB_CURSO
(
TB_ID_CURSO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_NOME_CURSO VARCHAR(85) NOT NULL
);

CREATE TABLE TB_TIPO_DE_AULA
(
TB_ID_TIPOAULA INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_ESTILO_AULA VARCHAR(40) NOT NULL
);

CREATE TABLE TB_DIARIO_DE_AULA
(
TB_ID_DIARIOAULA INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_PRESENCA_DIARIO VARCHAR(20) NOT NULL
);

CREATE TABLE TB_TURMA
(
TB_ID_TURMA INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_NOME_TURMA VARCHAR(40) NOT NULL,
TB_PARTICIPANTES_TURMA VARCHAR(16000) NOT NULL
);

CREATE TABLE TB_GRADE
(
TB_ID_GRADE INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_ALUNO_GRADE VARCHAR(40) NOT NULL,
TB_FUNCIONARIO_GRADE VARCHAR(40) NOT NULL,
TB_CURSO_GRADE VARCHAR(40)  NOT NULL,
TB_DIA_GRADE VARCHAR(40) NOT NULL,
TB_HORARIO_GRADE VARCHAR(10) NOT NULL 
);

CREATE TABLE TB_CHAT
(
TB_ID_CHAT INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_CONTEUDO_CHAT VARCHAR(15000) NOT NULL
);

CREATE TABLE TB_AULA
(
TB_ID_AULA INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TB_ID_ALUNO INTEGER NOT NULL,
TB_ID_TURMA INTEGER,
TB_ID_FUNCIONARIO INTEGER NOT NULL,
TB_ID_CURSO INTEGER NOT NULL,
TB_ID_TIPOAULA INTEGER NOT NULL,
TB_ID_DIARIOAULA INTEGER NOT NULL,
TB_DATA_AULA VARCHAR(20) NOT NULL,
TB_HORARIO_AULA VARCHAR(10) NOT NULL
);

ALTER TABLE TB_ALUNO
ADD CONSTRAINT PK_CURSO_FK_ALUNO
FOREIGN kEY (TB_ID_CURSO)
REFERENCES TB_CURSO(TB_ID_CURSO);

ALTER TABLE TB_ALUNO
ADD CONSTRAINT PK_RESPONSAVEL_FK_ALUNO
FOREIGN kEY (TB_ID_RESPONSAVEL)
REFERENCES TB_RESPONSAVEL(TB_ID_RESPONSAVEL);

ALTER TABLE TB_ALUNO
ADD CONSTRAINT PK_CONTA_FK_ALUNO
FOREIGN kEY (TB_ID_CONTA)
REFERENCES TB_CONTAS_DE_USUARIO(TB_ID_CONTA);

ALTER TABLE TB_FUNCIONARIO
ADD CONSTRAINT PK_CARGO_FK_FUNCIONARIO
FOREIGN kEY (TB_ID_CARGO)
REFERENCES TB_CARGO(TB_ID_CARGO);

ALTER TABLE TB_FUNCIONARIO
ADD CONSTRAINT PK_CONTA_FK_FUNCIONARIO
FOREIGN kEY (TB_ID_CONTA)
REFERENCES TB_CONTAS_DE_USUARIO(TB_ID_CONTA);

ALTER TABLE TB_AULA
ADD CONSTRAINT PK_ALUNO_FK_AULA
FOREIGN kEY (TB_ID_ALUNO)
REFERENCES TB_ALUNO(TB_ID_ALUNO);

ALTER TABLE TB_AULA
ADD CONSTRAINT PK_TURMA_FK_AULA
FOREIGN kEY (TB_ID_TURMA)
REFERENCES TB_TURMA(TB_ID_TURMA);

ALTER TABLE TB_AULA
ADD CONSTRAINT PK_FUNCIONARIO_FK_AULA
FOREIGN kEY (TB_ID_FUNCIONARIO)
REFERENCES TB_FUNCIONARIO(TB_ID_FUNCIONARIO);

ALTER TABLE TB_AULA
ADD CONSTRAINT PK_CURSO_FK_AULA
FOREIGN kEY (TB_ID_CURSO)
REFERENCES TB_CURSO(TB_ID_CURSO);

ALTER TABLE TB_AULA
ADD CONSTRAINT PK_TIPOAULA_FK_AULA
FOREIGN kEY (TB_ID_TIPOAULA)
REFERENCES TB_TIPO_DE_AULA(TB_ID_TIPOAULA);

ALTER TABLE TB_AULA
ADD CONSTRAINT TK_DIARIOAULA_FK_AULA
FOREIGN kEY (TB_ID_DIARIOAULA)
REFERENCES TB_DIARIO_DE_AULA(TB_ID_DIARIOAULA);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
''
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'BANJO'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'CAVACO'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'CONTRABAIXO'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'GUITARRA'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'UKULELE'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'VIOLÃO'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'VIOLA CAIPIRA'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'VIOLINO'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'BATERIA'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'PIANO'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'TECLADO'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'FLAUTA'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'SAXPHONE'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'CANTO'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'TEORIA MUSICAL'
);

INSERT INTO TB_CURSO
(
TB_NOME_CURSO
)
VALUES
(
'MUSICALIZAÇÃO INFANTIL'
);

INSERT INTO TB_CARGO
(
TB_NOME_CARGO
)
VALUES
(
''
);

INSERT INTO TB_CARGO
(
TB_NOME_CARGO
)
VALUES
(
'GERENTE'
);

INSERT INTO TB_CARGO
(
TB_NOME_CARGO
)
VALUES
(
'AUXILIAR'
);

INSERT INTO TB_CARGO
(
TB_NOME_CARGO
)
VALUES
(
'PROFESSOR'
);

INSERT INTO TB_RESPONSAVEL
(
TB_NOME_COMPLETO_RESPONSAVEL,
TB_EMAIL_RESPONSAVEL, 
TB_TELEFONE_RESPONSAVEL
)
VALUES
(
'',
'',
''
);

INSERT INTO TB_CONTAS_DE_USUARIO
(
TB_NOME_CONTA,
TB_SENHA_CONTA,
TB_CARGO_CONTA 
)
VALUES
(
'',
'',
''
);

INSERT INTO TB_ALUNO
(
TB_NOME_ALUNO,
TB_SOBRENOME_ALUNO,
TB_EMAIL_ALUNO,
TB_TELEFONE_ALUNO,
TB_DT_NAS_ALUNO,
TB_CPF_ALUNO,
TB_RG_ALUNO,
TB_CIDADE_ALUNO,
TB_BAIRRO_ALUNO,
TB_CEP_ALUNO,
TB_ENDERECO_ALUNO,
TB_ID_CURSO,
TB_STATUS_ALUNO,
TB_DT_MATRICULA_ALUNO,
TB_ID_RESPONSAVEL,
TB_ID_CONTA
)
VALUES
(
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'', 
1,
'',
'',
1,
1
);

INSERT INTO TB_FUNCIONARIO
(
TB_NOME_FUNCIONARIO,
TB_SOBRENOME_FUNCIONARIO,
TB_EMAIL_FUNCIONARIO,
TB_TELEFONE_FUNCIONARIO,
TB_DT_NAS_FUNCIONARIO,
TB_CPF_FUNCIONARIO,
TB_RG_FUNCIONARIO,
TB_CIDADE_FUNCIONARIO,
TB_BAIRRO_FUNCIONARIO,
TB_CEP_FUNCIONARIO,
TB_ENDERECO_FUNCIONARIO,
TB_ESTADO_CIVIL_FUNCIONARIO,
TB_NOME_CURRICULO_FUNCIONARIO,
TB_ARQUIVO_CURRICULO_FUNCIONARIO,
TB_ID_CARGO,
TB_STATUS_FUNCIONARIO,
TB_DT_ADMISSAO_FUNCIONARIO,
TB_ID_CURSO,
TB_ID_CONTA
)
VALUES
(
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'', 
'',
'', 
'',
1,
'',
'',
1,
1
);